project_id = "jitsslwweidvderlgvzv"

[functions.rank]
verify_jwt = false

[functions.nearby]
verify_jwt = false

[functions.import_nutritionix]
verify_jwt = false

[functions.import_brand_menu]
verify_jwt = false

[functions.set_price]
verify_jwt = false

[functions.seed_sample]
verify_jwt = false

[functions.db_status]
verify_jwt = false

[functions.seed_demo]
verify_jwt = false
